mgr = None
root = None
side_frame = None
chat_frame = None
chat_history = None
listbox = None
entry = None
status = None
logo_label = None
toggle_btn = None
settings_btn = None
gate_frame = None
login_frame = None
disc_frame = None
setup_frame = None
tabs = None
settings_tab = None
alias_to_real: dict[str, str] = {}
real_to_alias: dict[str, str] = {}
chat_images: list = []
current_user: str | None = None
gallery_images: list = []
gallery_container = None
attach_row = None
native_tk_font = None
workspace_frame = None
title_bar = None
drag_offset: tuple[int, int] | None = None
login_password_entry = None
status_scroll = None
user_label = None
pending_user: str | None = None
encryption_key: bytes | None = None
